commaai/connect

src/components/RouteStatistics.tsx

The bottom spacing would be very tight when on a small width device.
https://github.com/commaai/new-connect/assets/142481257/63afe286-c64e-4f8d-b7c5-7a66716aead2

Text/btm-padding: Fixed spacing when screen width is small

---

src/components/material/IconButton.tsx
src/pages/dashboard/Dashboard.tsx

---
---
- **New icon:** onClose button should not be a `menu` icon which suggests another menu flow. It should be a back arrow which suggests the drawer to close and to return back to where you came from.
- **Added .5rem padding**: Current buttons did not have any padding so when mouse hoovered or on press the icon would show the alternative state with little padding shown above.

IconButton: add padding and update dashboard drawer close icon

---

src/index.css

This shows up for both mobile and desktop.
https://github.com/commaai/new-connect/assets/142481257/801b3ad6-ea1a-444c-8a8c-52c6bbde3c45

Fixed overflow when scrolling up

---

src/api/derived.ts
src/api/route.ts
src/components/RouteCard.tsx
src/components/Timeline.tsx
src/pages/dashboard/components/RouteList.tsx
src/types.d.ts
src/utils/date.ts

- update `Route` type to match `/v1/route/<routeName>` response type
- declare `RouteSegments` type to match `/v1/devices/<dongleId>/routes_segments` response type
- implement `getRouteDuration` helper for `Route`
- fix `Timeline` and `RouteList`

update route API types and fix timeline

---

src/pages/dashboard/activities/DeviceActivity.tsx

**Problem:**
Whenever visiting `RouteActivity` page then clicking the back button to go back to `Dashboard` you will see the text "Device" show then disappear. The flashing text is located in the top left next to menu button.
**Solution:**
Change the fallback text to an empty fragment because flashing the text "Device" doesn't provide any useful information to users. I thought about changing the fallback text to "loading..." but didn't think having a loading text was necessary since all we are waiting for is a device name, or waiting for nothing if user doesn't have an alias for their comma device.
<br>
https://github.com/commaai/new-connect/assets/142481257/77ba4387-040c-4f2d-baa7-83257a84a91f
<br>
https://github.com/commaai/new-connect/assets/142481257/9d60190b-69b0-403a-82d0-f1f3e9e1d39 …

TopAppBar: fix flashing "Device" text in Dashboard

---

.github/workflows/preview.yaml

To my understanding this is so pose to help by increasing the rate limit since I added the Github Token. I also added a retry mechanism instead of trying to rerun actions manually. I noticed that Cameron also ran into the secondary rate limit so hopefully this would help us not hit that limit anymore.
I'm not entirely confident this would help so feel free to close this. My previous PRs are now able to generate the Preview Link.
Reference Link: [docs.github.com](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#about-secondary-rate-limits)

CI(Preview): add retries to find PR script

---

.github/workflows/preview.yaml
src/ci/screenshots.cjs

Chromium's deps are present in the runner base image so much faster than using webkit. 
Speed up is 53s -> 27s https://github.com/signed-long/new-connect/actions/runs/9786617432/job/27021805208

Preview speedup - use chromium not webkit

---

src/pages/dashboard/Dashboard.tsx
src/pages/dashboard/components/DeviceList.tsx
src/utils/storage.ts

Write the dongle ID to local storage when a device is selected, and use that as the default when loading the app (unless a dongle is already set in the URL)
closes #45

Dashboard: default to last selected device

---

src/components/RouteCard.tsx
src/pages/dashboard/components/RouteList.tsx
src/types.d.ts

Closes #53 
These change deprecate use of `segment_start_times`, `segment_end_times` and `segment_numbers` in preparation for removing these fields from the network payload.

Deprecate use of RouteSegments segment times fields

---

.github/workflows/build.yaml
.github/workflows/preview.yaml

It's possible to write the status back to the PR using the github checks api, but I think this is simpler.
Resolves #80

CI: Call preview from build workflow

---

.github/workflows/build.yaml

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idsecretsinherit
Has access to a test secret on my fork: https://github.com/signed-long/new-connect/actions/runs/9932149610/job/27433070605#step:2:1

CI: add `secrets: inherit` to preview workflow call

---

.github/workflows/build.yaml
.github/workflows/preview.yaml

Job is still failing due to secrets not being available to fork's PRs. This puts the preview job back to the working state and won't block PRs. 
Can reopen #80 and do it with something like this: https://stackoverflow.com/questions/74867744/how-can-i-attach-a-manual-workflow-run-to-a-pull-requests-status-checks

CI: Revert envoking preview job with workflow_call

---

eslint.config.js
src/api/derived.ts

This is similar to the default typescript compiler behaviour

lint: ignore unused vars starting with underscore

---

.github/workflows/preview.yaml

Adds a status check to the PR for the preview job. 
https://github.com/signed-long/new-connect/pull/19/checks

CI: add PR check to preview job

---

.github/workflows/preview.yaml
src/ci/screenshots.cjs

- Wait for network idle
- Spawn one browser instead of two
- Improve usability/ability to run locally
- Remove dependency on /usr/bin/chromium (some people use windows... 🫠)
- Run different contexts in parallel to save ~15s (can use more cores when running locally)
You can also test it against a production build locally like this:
```
$ bun run build && bun vite preview
(in another terminal)
$ node ./src/ci/screenshots.cjs http://localhost:4173
```
Testing on my fork: https://github.com/incognitojam/new-connect/pull/3

fix(screenshots): support running script locally, cleanup code

---

src/pages/dashboard/activities/PairActivity.tsx

When on mobile text gets cut off. Fixed with adding padding. Horizontal padding prevents text cutoff, while increasing bottom padding helps make sure the iPhone Home Screen bar doesn't get too close.
https://github.com/user-attachments/assets/0ba1f053-afe4-43b7-bb8d-711b4148019a

PairActivity: prevent text cutoff on mobile

---

src/components/material/Button.tsx
src/components/material/List.tsx
src/pages/dashboard/Dashboard.tsx

This resolves issue https://github.com/commaai/new-connect/issues/134 and #82 
**Before**
**After**

fix: buttons squished

---

src/pages/dashboard/components/RouteList.tsx

This PR improves the RouteList component by introducing infinite scrolling and a responsive grid layout. These changes enhance user experience, performance, and maintainability while reducing manual interactions.

feat(RouteList): implement infinite scrolling

---

src/components/material/Drawer.tsx

| Current UI | Proposed UI |
|------------|-------------|
| ![chrome-scroll-bug](https://github.com/user-attachments/assets/05c44062-9004-4e42-9618-c0f42b0ad607) | ![chrome-no-shifts](https://github.com/user-attachments/assets/69f37acb-befc-4d79-8c65-0f4ec5e1167d) |
<br>
- Same shifting scrollbar bug as PR #144 
- This fixes the shifting of the scrollbar when zooming out
- Bug shows for Chrome, Firefox and Safari

fix(Drawer): prevent scrollbar shifting when zooming out

---

src/components/material/Drawer.tsx
src/pages/dashboard/Dashboard.tsx
src/pages/dashboard/activities/RouteActivity.tsx
src/pages/dashboard/activities/SettingsActivity.tsx
src/pages/dashboard/components/ActivityBar.tsx

Make use of the space available on desktop to show route list side-by-side with the route video/map/device settings

Dashboard: use two pane layout on larger screens

---

src/pages/dashboard/components/RouteList.tsx

Load more elements on larger screens to ensure the entire height is filled and the intersection observer is off screen. If after the elements are loaded the intersection observer is still on screen it will never be triggered.
This bug only affected large monitors on the smallest zoom levels, but the changes mean devices with smaller screens will load fewer elements too, which might improve performance/load times.

fix(RouteList): adjust page size for screen height

---

src/components/DeviceLocation.tsx
src/components/material/Card.tsx
src/components/material/IconButton.tsx
src/components/material/List.tsx
src/components/material/TopAppBar.tsx
src/pages/dashboard/components/DeviceList.tsx

- fixes device list overflow
- fixes text overflow in app bar
- force icons to have correct width and height - don't get squashed when there isn't enough space for neighbouring text
- fix the DeviceLocation card to truncate long device names, wrap text, and cleanup code

fix: various text wrapping and overflow issues

---

src/components/RouteStatistics.tsx
src/pages/dashboard/activities/RouteActivity.tsx
src/utils/format.spec.ts
src/utils/format.ts

preparing to refactor to remove dayjs and use web standards (e.g. `Intl.DateTimeFormat`)

test(format): add unit tests for formatDistance/Duration

---

src/map/geocode.spec.ts

- Was getting the above error in PR #164 . Seems like the current address are now wrong because mapbox got more accurate, which then changed to the actual address of the white house. Below is the address of the white house also found [here](https://www.usa.gov/agencies/white-house).
- Got the same error when I did a blank commit in PR #190 
<br>

Fix: update geocoding test to correct address

---

.github/workflows/preview.yaml

- When Build workflow fails, Preview workflow still triggers
- `needs.preview.outputs.check_id` is undefined (because preview job couldn't run)
- Results in JavaScript syntax error from: check_run_id: ,
- Ran into this problem wth PR #164 when it didn't pass the test the first time, after I committed the updated white house address, I got the below error from Preview workflow
<br><br>
- Add github.event.workflow_run.conclusion == 'success' to skip when triggering workflow failed
- Put success check first for efficient short-circuit
- Code also found in [commai/website repo](https://github.com/commaai/website/blob/master/.github/workflows/preview.yaml#L112)

CI: skip if triggering workflow failed

---

src/components/RouteActions.tsx

- Copy icon is not centered with the below toggles
- Adjusted spacing to still trigger the words breaking into the new line while keeping icon centered above the toggles
---
<br>
https://github.com/user-attachments/assets/2bfdbda5-3a98-410b-90df-d2bd1e50c43b

UI: Center copy icon

---

.github/workflows/build.yaml

Job now uses cached playwright files to run test. Key is generated from the hash of `bun.lockb` file.  Issue: #181 
I am not sure if this approach is better than directly having key as the playwright version contained in `package.json`. Any changes in the lock file will trigger `bun playwright install` even if there are no playwright specific changes in that file.
build / test reduced from 37secs ----> 19secs

Cached playwright in test job.

---

src/components/RouteVideoPlayer.tsx
src/pages/dashboard/Dashboard.tsx
src/pages/dashboard/activities/RouteActivity.tsx

Added a quick enhancement to get the start time from URL. The time is in seconds. Issue: #194 
For the "zoom" into part, I am thinking we could do a window that will be on the timeline bar and the rest of the bar grayed out while listening for the current time. If it reaches the end time, we could put it back to the start time of the window.

Added start time in video player

---

src/utils/format.ts

Tested with `chromium --accept-lang en-CA` shows KM correctly
Closes #214

feat: format distance in km, detect region from navigator.language

---

src/api/athena.ts
src/api/devices.ts
src/api/file.ts
src/api/index.ts
src/api/route.ts
src/api/upload.ts
src/ci/check_bundle_size.ts
src/components/RouteActions.tsx
src/components/RouteUploadButtons.tsx
src/pages/dashboard/activities/RouteActivity.tsx
src/types.d.ts

keeping in mind the LoC limits, minimized some lines in nearby APIs

feat: upload user files

---

src/api/athena.ts
src/pages/dashboard/activities/RouteActivity.tsx

Call `setRouteViewed` athena method with the route ID when opening a route.
TODO:
Closes #221

feat: notify device of viewed routes

---

index.html
src/components/material/Icon.tsx
src/pages/auth/login.tsx
vite.config.ts

Specify icon names to load from Material Symbols font, reducing the font payload from ~1MB to ~9KB.
Note that all icons used *must* be added to this list.
**Before**
**After**

perf: reduce Material Symbols font payload

---

src/components/DeviceLocation.tsx
src/components/RouteActions.tsx
src/components/RouteStaticMap.tsx
src/components/RouteUploadButtons.tsx
src/components/material/Drawer.tsx
src/components/material/Icon.tsx
src/components/material/IconButton.tsx
src/components/material/NavigationBar.tsx
src/pages/auth/login.tsx
src/pages/dashboard/Dashboard.tsx
src/pages/dashboard/activities/DeviceActivity.tsx
src/pages/dashboard/activities/PairActivity.tsx
src/pages/dashboard/activities/RouteActivity.tsx
src/pages/dashboard/activities/SettingsActivity.tsx
vite.config.ts

This type-checked prop will allow us to avoid using new icons without adding them to the icons list. The Material Symbols font URL can be generated from the same list of icon names.

refactor: add type-checked name prop to Icon component

---

src/types.d.ts

athena offline queue can hold any types of athena calls.

refactor: athena types, add missing priority field

---

src/components/DeviceStatistics.tsx
src/components/RouteStatistics.tsx
src/components/StatisticBar.tsx
src/utils/format.spec.ts
src/utils/format.ts

Would love this StatisticBar for https://github.com/commaai/connect/pull/203/ to reuse spacing and styling
also inlined a few types to reduce LoC

refactor: create StatisticsBar

---

src/pages/dashboard/Dashboard.tsx
src/pages/dashboard/components/DeviceList.tsx

Instead of prop drilling, we can just fetch the list of devices where they are used. We should use a query library to cache/de-duplicate requests.

cleanup(dashboard): fetch devices where they are used

---

src/components/UploadQueue.tsx
src/components/material/Icon.tsx
src/pages/dashboard/activities/DeviceActivity.tsx

last part of https://github.com/commaai/connect/issues/51
handles device disconnected, no items in queue, and rendering a list of files being uploaded
possible features to add in the future:
- nice animations
- displaying the offline queue
- simplify the polling loop with something like https://tanstack.com/query/latest/docs/framework/solid/overview

feat: upload queue

---

tailwind.config.ts

without this, the `text-*` classes on child elements don't reset letter spacing set in parent

fix: reset typography letter spacing

---

src/api/auth/client.ts

Fixes an issue related to CORS on stricter browsers (e.g. Safari)
Resolves #253 seen in #252

fix: use correct auth API endpoint

---

src/pages/dashboard/components/RouteList.tsx

- was using `ring-1` changed to `border`
- seems like it gets jaggedy and pixelated on certain screens
- using `border` better/consistent for lower DPI screens
From Shane:

Fix pixelated flag icon border for certain screens

---

src/ci/check_bundle_size.ts
src/components/UploadQueue.tsx

https://github.com/commaai/connect/issues/51
tested locally:
1. when device offline, upload request puts items in offline queue, showing them in the queue in the UI with a "Queued" message
2. when device comes online, status switches to "Waiting" until Athena server pushes the queued requests
3. finally, messages start coming in and processing as normal

feat: poll offline queue

---

src/components/material/Icon.tsx
src/pages/auth/auth.tsx
src/pages/dashboard/activities/SettingsActivity.tsx

resolves: https://github.com/commaai/connect/issues/274
removed `sync` entirely because the `animate-spin` spins clockwise. instead of writing a custom animation, just using `autorenew` as it's essentially the same icon with arrows moving clockwise.
animating the processing subscription icon as well

fix: auth / processing icons spin correct direction

---

src/components/UploadQueue.tsx

resolves point 2: https://github.com/commaai/connect/issues/258
some very basic guarding like don't send request. adding dedupe will add extra code that doesn't increase value (if a cancel request fails or one is in flight, it's not a big deal)

feat: cancel item, all, w/ stats bar

---

src/api/index.ts
src/components/RouteActions.tsx
src/pages/dashboard/activities/RouteActivity.tsx

Ideally we only make one /route query when you load a route, not three. This PR removes one.
https://github.com/commaai/connect/pull/298#discussion_r2019681192

Remove 1/2 duplicate route query

---

src/pages/dashboard/components/RouteList.tsx

If there was an uncaught error, the Suspense would never get triggered and be stuck in fallback state forever
before:
after:

Fix routes not loading because one is missing events.json

---

src/api/derived.ts
src/pages/dashboard/components/RouteList.tsx

Better version of https://github.com/commaai/connect/pull/311 that attempts to continue to use other available events files
Now the problem route in the other PR can be fully loaded:

Handle errors for individual files

---

src/components/RouteStatistics.tsx
src/pages/dashboard/components/RouteList.tsx

This reverts commit fcd306d92ae87cfa9a542a359d041b15d428459b.
There was another instance of RouteStatistics that didn't set timeline.

Revert "Remove duplicate events.json queries (#289)"

---

src/api/derived.ts

Returning [] as an element was a mistake

api: getDerived should filter missing data

---

src/api/derived.ts
src/api/devices.ts
src/api/profile.ts
src/api/route.ts
src/components/DeviceLocation.tsx
src/components/RouteActions.tsx
src/components/RouteUploadButtons.tsx
src/components/Timeline.tsx
src/pages/dashboard/Dashboard.tsx

This makes the code cleaner, although we should still look at adding ErrorBoundaries to show when an error has occurred

cleanup: return undefined for failed requests

---

src/pages/dashboard/activities/RouteActivity.tsx

very little benefit now that HLS.js is loaded lazily instead

cleanup: don't lazy import RouteVideoPlayer

---

src/components/UploadQueue.tsx

resolves: https://github.com/commaai/connect/issues/296
adding some contrast to the cancel btn as well, it blended in too well.

fix: hide cancel btn for in progress uploads, rework contrast

---

src/pages/dashboard/Dashboard.tsx

Avoids recreating the RouteActivity when changing between selected routes

perf: make switching route snappy

---

src/components/UploadQueue.tsx

comma's firehose uploads go to a different host; the URL structure is different
this is also a much cleaner way of identifying when firehose data is getting uploaded

fix: firehose parsing

---

src/components/UploadQueue.tsx
test.sh
tsconfig.json

- run `tsc --noEmit` as a "type-checker" in the test suite (won't block the build if building works, so we can preview even if types aren't perfect)
- fix the two complaints

ci: check TypeScript type errors

---

src/components/RouteUploadButtons.tsx

introduced in https://github.com/commaai/connect/commit/0507b64e96f8009727ec871610e69353a1768676
buttons appear to not work but we aren't requesting any files types to upload when the helper is called
`concat()` does not modify underlying arrays

fix: concat usage

---

src/App.browser.test.tsx
src/App.tsx

simulate the real app as closely as possible, important when we add more context providers like with TanStack Query
**Verification**
made sure tests fail when navigator.onLine is false, which causes elements to not render

test: include AppLayout in browser tests

---

src/components/RouteVideoPlayer.tsx

resolves: https://github.com/commaai/connect/issues/381
https://github.com/user-attachments/assets/2068ce76-9ef2-48b8-aee8-765261004c13

fix: cant play / pause by clicking entire surface

---

src/api/derived.ts
src/components/RouteStatistics.tsx
src/components/Timeline.tsx
src/pages/dashboard/activities/RouteActivity.tsx
src/pages/dashboard/components/RouteList.tsx
src/utils/format.ts

Split from https://github.com/commaai/connect/pull/392
Reduces the span of time we're spending on json queries for a route of 12 segs from 35ms to 10ms (from first query queue to last query start)

RouteList: remove duplicate event.json queries

---

pwa-assets.config.ts

workaround a bug in the Vite PWA asset generator which included `-light` in the path to the image in `dist/index.html`, but the assets did not have `-light` in the filename.
closes #380

fix: correct path to Apple splash PWA assets

---

src/App.browser.test.tsx
src/api/devices.ts
src/pages/dashboard/Dashboard.tsx
src/pages/dashboard/activities/DeviceActivity.tsx
src/pages/dashboard/activities/SettingsActivity.tsx
src/pages/dashboard/components/DeviceList.tsx
src/utils/device.ts

Breaks the fallback where we need to differentiate between loading (undefined device) and actually denied/unknown/shared device (undefined device)

Revert shared device

---

src/pages/dashboard/Dashboard.tsx

accidentally leftover in #160
SuspenseList controls the order in which content is revealed (when the fallback is removed), so it would appear that some Suspense were triggered when they were just blocked by another Suspense (depending on direction of `revealOrder`)

fix: remove extraneous SuspenseList in Dashboard

---

src/pages/dashboard/Dashboard.tsx
src/pages/dashboard/activities/RouteActivity.tsx

suspense works in RouteActivity now. `keyed` makes Solid re-render the component from scratch, so in this case the `RouteActivity` is re-rendered from scratch. i think the re-use between navigations was causing issues with resources in `RouteActivity`
we need `keyed` at the `dongleId` above for a similar reason.
i think it's technically an escape hatch, but we can spend time later on removing this.
need to rework RouteStatistics, engaged shows NaN% on immediate load
https://github.com/user-attachments/assets/bb0670c6-a869-4c22-a5c6-0be73582c4ac

fix: RouteActivity suspense not blocking any longer

---

src/pages/dashboard/activities/RouteActivity.tsx

loads properly on top of https://github.com/commaai/connect/pull/474
https://github.com/user-attachments/assets/aadf039b-7673-49c5-a67b-79ad3c45f68e

fix: add back RouteStaticMap Suspense animation

---

src/components/RouteStatistics.tsx

resolves: https://github.com/commaai/connect/issues/477
handles the NaN while loading, can't divide by zero 😄

fix: StatisticsBar fallback

---

src/components/RouteVideoPlayer.tsx
src/pages/dashboard/Dashboard.tsx
src/pages/dashboard/activities/RouteActivity.tsx

partial version of https://github.com/commaai/connect/pull/484

Add route selection via URL

---

src/components/RouteVideoPlayer.tsx

Show an error when the browser can't play the video and doesn't support MSE (so we can't use Hls.js either), instead of just logging the error to the console

fix: show video unsupported error message

---

index.html

resolves: https://github.com/commaai/connect/issues/458
https://ogp.me/
https://indieweb.org/The-Open-Graph-protocol#Does_not_support_SVG_images

fix: icon in meta

---

src/pages/dashboard/components/RouteList.tsx
src/utils/format.spec.ts
src/utils/format.ts

my take on the route color, but attempting to be simpler, no deps (thx gpt)
pending:

feat: color route card based on time

---

src/utils/format.spec.ts
src/utils/format.ts

I selected averages for all seasons and locations, but then it's not good anywhere. For now it's calibrated to accurately depict thumbnails in San Diego in the summer

Daylight indicator: just make it good for current season and location

---

src/components/material/ButtonBase.tsx

for https://github.com/commaai/connect/pull/517
https://docs.solidjs.com/concepts/control-flow/dynamic

feat: add `Anchor` props to `ButtonBase`

---

src/api/derived.ts
src/components/RouteStatisticsBar.tsx
src/pages/dashboard/activities/RouteActivity.tsx
src/pages/dashboard/components/RouteList.tsx

We will use these stats for getting things like the route duration from the logs, I think this is a better name

refactor: rename TimelineStatistics to RouteStatistics

---

src/api/derived.ts
src/components/Timeline.tsx
src/pages/dashboard/activities/RouteActivity.tsx
src/pages/dashboard/components/RouteList.tsx

- get route duration from log events (instead of relying on time)
- use new route duration for timeline and engaged % (fixes jitter)
- we still use reported route duration (from route table) to show in route stats sooner, while we fetch the events
closes #247 and fixes the bug with flickering engaged %

feat(statistics): get route duration from log events

---

src/api/types.d.ts
src/components/RouteActions.tsx
src/utils/format.ts

- API returns `null` for many
- `route.start_time` can be null too
- there is no `route.is_preserved` (this was included in `routes_segments` endpoint)

fix(types): update route types

---

src/components/RouteStatisticsBar.tsx
src/pages/dashboard/activities/RouteActivity.tsx
src/pages/dashboard/components/RouteList.tsx
src/utils/format.ts

Use route duration from logs for statistics, if available
after #528

feat(statistics): use log duration in route stats

---

src/api/athena.ts
src/pages/dashboard/activities/DeviceActivity.tsx

- move `takeSnapshot` method to `api/athena.ts` (using `makeAthenaCall` helper)
- use a store to manage snapshot state, reducing complexity
- use `<Show>` for conditional rendering

cleanup(snapshot): move method to athena, use store

---

src/pages/dashboard/Dashboard.tsx

resolves: https://github.com/commaai/connect/issues/506, https://github.com/commaai/connect/issues/533
combines https://github.com/commaai/connect/pull/512 and https://github.com/commaai/connect/pull/536
won't introduce network flakiness since we don't make any requests to check logged in status

fix: login redirect

---

src/api/profile.ts
src/pages/dashboard/Dashboard.tsx
src/pages/dashboard/activities/RouteActivity.tsx
src/utils/reactivity.ts

Narrows the type of a resource so that you can "safely" read from it without triggering Suspense
Also added an error boundary for the profile

refactor: add reactivity helper isResolved

---

src/components/RouteVideoPlayer.tsx

fix(RouteVideoPlayer): ceil duration

---

src/index.css

This ensures elements don't resize while the icon font is loading

fix: set max-width on Icon

---

src/pages/dashboard/activities/PairActivity.tsx

This shows an error message instead of just a blank screen when permission request is denied - will follow up with another PR to show a more informative error if we detect permission blocked (this is actually tricky)

fix(PairActivity): catch errors starting QR scanner

---

src/components/RouteUploadButtons.tsx

- No need for `states` object inside the store
- Step towards #407

cleanup(RouteUploadButtons): simplify store and types

---

src/components/UploadQueue.tsx

create* has been deprecated in solid-query in favour of use*, presumably because it meant they had to keep two sets of docs?
https://github.com/TanStack/query/pull/8950/

chore(solid-query): switch to useQuery

---

src/api/devices.ts
src/api/index.ts
src/api/types.d.ts
src/pages/dashboard/activities/DeviceActivity.tsx
src/pages/dashboard/components/DeviceList.tsx
src/utils/device.ts

We can just calculate `is_online` when we fetch the device instead of attaching `fetched_at: number` to every API response and re-calculating `isDeviceOnline` in different places

cleanup: remove API fetched_at and add Device.is_online

---

src/App.browser.test.tsx
src/pages/dashboard/Dashboard.tsx
src/pages/dashboard/activities/DeviceActivity.tsx
src/pages/dashboard/activities/PairActivity.tsx
src/pages/dashboard/activities/RouteActivity.tsx
src/pages/dashboard/activities/SettingsActivity.tsx
src/pages/dashboard/components/DeviceList.tsx
src/pages/dashboard/data.ts
src/utils/device.ts

This removes a couple of duplicate API fetches for profile, devices and the current device. If the current device is in the list already returned (my devices) then that will be used instead, too.
19 requests to api.comma.ai down from 23 (including OPTIONS) on the demo route
https://579.connect-d5y.pages.dev/1d3dc3e03047b0c7/2023-07-27--13-01-19

refactor(Dashboard): shared data

---

src/components/material/Button.tsx

- ~~We set the background colour on hover, changing opacity makes that harder to see~~ will fix separately
- Improved bg color for text button (fixes "Cancel all" contrast) (matches [spec](https://m3.material.io/components/buttons/specs#398d84eb-fc8a-4c8a-bfb4-82d2e85dee4d))

fix(Button): improved text btn contrast

---

src/pages/dashboard/activities/SettingsActivity.tsx

- Explain that prime is cancelled immediately and you receive a pro-rated refund
- Update buttons text to be shorter but clear
- Use text buttons (less ugly)
| new | old |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/59bf8323-5afc-4a28-8a4e-94d5791202be) |![image](https://github.com/user-attachments/assets/284d132c-f92e-4e87-98bd-5f2531935b50) |

fix(prime): improve copy and design of cancel dialog

---

src/pages/dashboard/activities/SettingsActivity.tsx

fix(settings): use text style button

---

src/components/material/Dialog.tsx
src/pages/dashboard/activities/SettingsActivity.tsx

Adds a reusable Dialog component (intended for other actions like unpairing)
- On mobile it no longer unnecessarily takes up the entire screen height
- Supports closing with escape key press (thanks to native `<dialog>` element)
| mobile | web |
| --- | --- |
|![Screen Shot 2025-04-15 at 16 53 40](https://github.com/user-attachments/assets/13faabd1-2fce-4417-a574-8a1d85bbf4d8) | ![Screen Shot 2025-04-15 at 16 58 54](https://github.com/user-attachments/assets/5608b6ab-ec4a-42d2-ab60-97c4ac116f91) |

refactor(Dialog): add component, update design

---

src/components/material/Dialog.tsx
src/pages/dashboard/activities/SettingsActivity.tsx

Eliminate the need to use `<Show>` by fixing the styles on `<dialog>`: the `flex` class caused the dialog to be visible all the time. Nesting the content inside an additional div allows us to center the content without applying `flex` to the `<dialog>` element.

fix(Dialog): remove flex class, hidden by default

---

src/components/material/Icon.tsx
src/pages/dashboard/activities/DeviceActivity.tsx

closes #433
| online | loading | offline |
| --- | --- | --- |
| ![image](https://github.com/user-attachments/assets/af7c6a14-115c-4541-857e-5f1706cca254) | ![image](https://github.com/user-attachments/assets/aae20b26-dde6-4749-a89e-d63271255bb7) | ![image](https://github.com/user-attachments/assets/6eda7b5a-ceb8-4959-876c-d75be8c814c3) |
For an extra 10 lines we can cache the results between changing device, but not sure it's worth it for this specific thing - not sure whether we are trying to replace tanstack or not

feat(Device): add battery voltage indicator
