commaai/connect

src/api/auth/client.ts, src/api/profile.ts, src/pages/dashboard/Dashboard.tsx
This fixes the blank page you see if you haven't logged in
=> fix: redirect to /login if can't fetch user profile

src/theme/index.ts
Map correctly uses dark style now
=> fix(theme): read theme from document.body

.github/workflows/build.yaml, .github/workflows/preview.yaml
cloudflare/pages-action hasn't been updated and is using deprecated Node16
=> CI: use cloudflare/wrangler-action

eslint.config.js, package.json
https://github.com/eslint/eslint/discussions/17429
Fixes #78
=> Eslint: fix ignored directories 

.github/workflows/preview.yaml, src/ci/screenshots.cjs
See #96 
Testing here: https://github.com/incognitojam/new-connect/pull/3
- Revert timeout
- Removed an unnecessary `bun install` (which also runs `husky` postinstall which runs `bun lint`) and saved 7s in preview job
=> fix(screenshots): support running script locally, cleanup code

.github/workflows/preview.yaml
Described here: https://github.com/orgs/community/discussions/25220#discussioncomment-11285971
=> CI: use `gh pr view` to get PR number and avoid rate limit

src/pages/dashboard/Dashboard.tsx
This resolves issue https://github.com/commaai/new-connect/issues/133
**1280px**
**3840px**
=> fix(dashboard): set content max-width

index.html, src/pages/auth/login.tsx
This resolves issue https://github.com/commaai/new-connect/issues/125
**After**
=> fix(login): responsive design

src/pages/dashboard/activities/PairActivity.tsx
=> fix(PairActivity): video container layout

src/pages/dashboard/components/RouteList.tsx
=> fix(RouteList): duplicate entries

src/components/material/Drawer.tsx, src/pages/dashboard/Dashboard.tsx
=> feat: use modal drawer on smaller screens

src/components/material/Card.tsx
broke in 6c77f747a91a36b09b0edcc5c1a381dc23664b63
=> fix(RouteList): add state-layer back to card

.github/workflows/preview.yaml, src/index.css
=> CI: cancel earlier PR preview jobs

src/map/geocode.spec.ts
Updated coords to match Google Maps but it's still changed zip code, so removing it for now...
=> test(geocode): remove whitehouse case, keeps changing

src/ci/check_bundle_size.ts
=> fix: run bundle size check on MacOS

src/components/RouteActions.tsx
=> RouteActivity: updated toggles design

src/ci/check_bundle_size.ts, src/ci/check_lines.ts, src/ci/dependency_report.ts
[fix: check lines works locally, also removes extra /](https://github.com/commaai/connect/commit/a347e4128bd38e2e5053bc3718d78a5af8e9a610)
[fix: remove extra / from bundle size](https://github.com/commaai/connect/commit/a0c269862b962a8bd93b2766e2a026a49a4514b3)
[feat: add unminified dependency file to dependency report](https://github.com/commaai/connect/commit/24419382782909a244584d1341023584bd5d479b) (nice for checking weight of dependency)
=> feat/fix: CI script improvements running locally

src/ci/check_lines.ts
I don't think there is a tokeniser we can use like tinygrad does to count lines and exclude comments
=> CI: exclude blank lines from line count

.github/workflows/diff.yaml, src/ci/check_lines.ts
- Update check_lines script to calculcate diff between two source trees
- Comment on PRs with diff
In future this same idea can be applied to the bundle size checker to show changes in the output.
Workflow copied from tinygrad
=> CI: comment lines diff

src/api/devices.ts, src/api/index.ts, src/components/material/Icon.tsx, src/pages/dashboard/activities/SettingsActivity.tsx
=> feat: add device unpair button

src/api/auth/client.ts, src/pages/auth/auth.tsx
| normal | error |
| --- | --- |
| ![Screen Shot 2025-03-27 at 22 13 48](https://github.com/user-attachments/assets/ba5378f2-79c4-4393-aabc-84c78668f917) | ![Screen Shot 2025-03-27 at 22 14 30](https://github.com/user-attachments/assets/002ff200-727f-4e38-98d1-f84eaa944729) |
=> feat: nice auth screen

src/components/RouteVideoPlayer.tsx, src/hls-light-types.d.ts, src/utils/hls.ts
=> perf: lazy import Hls.js in RouteVideoPlayer

src/components/RouteActions.tsx
resolves: https://github.com/commaai/connect/issues/260
=> feat: add useradmin external link on route actions

src/api/devices.ts, src/pages/dashboard/activities/DeviceActivity.tsx
=> fix: show device stats if has device access

src/components/UploadQueue.tsx, src/components/material/Icon.tsx
=> feat: change cancel upload icon to X, update spacing

src/api/index.ts, src/components/Timeline.tsx, src/pages/dashboard/activities/RouteActivity.tsx
pt. 2 of https://github.com/commaai/connect/pull/302
=> Remove 2/2 duplicate route queries

src/components/Timeline.tsx
split out from #283, closes #306
tested on:
=> refactor: re-write Timeline event handling

src/components/RouteVideoPlayer.tsx
Should improve performance around switching routes/reduce time for video to load.
Verified by setting `debug: true` in Hls options in `src/utils/hls.ts` and reviewing debug log.
=> perf: avoid re-creating HLS.js instance

live.sh
`--open` is in the dev script now
=> chore: update live script

src/components/RouteUploadButtons.tsx
same purpose as https://github.com/commaai/connect/pull/338 (GH closed my PR when i rebased and dropped the commit)
https://github.com/user-attachments/assets/31471d8a-cc93-492e-b880-04a0feeb4c62
=> fix: reset upload btn state on new route selection

src/api/auth/client.ts, src/api/auth/index.ts, src/api/config.ts, src/api/index.ts, src/api/route.ts, src/components/RouteActions.tsx, src/pages/dashboard/Dashboard.tsx
=> chore: rename BASE_URL to API_URL

src/pages/dashboard/activities/DeviceActivity.tsx
=> cleanup: remove unused suspense

src/components/Timeline.tsx
=> fix: remove Timeline event listeners on touchend

src/components/RouteVideoPlayer.tsx, src/components/Timeline.tsx, src/components/material/Icon.tsx, src/pages/dashboard/activities/RouteActivity.tsx, src/utils/format.ts, src/utils/hls.ts
Joins the `Timeline` and `RouteVideoPlayer` components into an integrated UI.
- Custom controls on video element, showing current time and duration, and pause/play button
- Tap video to toggle playback
- Added progress bar
- Updated Timeline design with cursor
Rebased #190 after changes in master.
Closes #306
=> feat: integrated route video player

index.html, public/manifest.json
=> fix: update theme color to match background

src/components/Timeline.tsx
https://github.com/commaai/connect/pull/283#issuecomment-2767036859
=> design: white timeline progress bar

src/components/Timeline.tsx, src/pages/dashboard/components/RouteList.tsx
| alternate | original |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/c95324d8-2e70-4980-9ee1-9bcd953e71b5) | ![image](https://github.com/user-attachments/assets/2d852004-f8d1-4c82-b6e2-0d96bd8a8aef) |
=> design: user flag icon

src/components/UploadQueue.tsx
resolves: https://github.com/commaai/connect/issues/360
=> feat: add scrollbar to queue

src/pages/dashboard/components/RouteList.tsx
- re-write to not have chained resources
- location() should have a suspense around it (unless we put a suspense around each RouteCard instead)
=> RouteCard suspense

src/api/derived.ts
=> fix: segments numbers is maxqlog + 1

src/App.browser.test.tsx, src/api/route.ts, src/pages/dashboard/Dashboard.tsx, src/pages/dashboard/activities/RouteActivity.tsx
This reverts commit 47db901ab2af90291104104f0f9a8b273e46bf52.
Closes https://github.com/commaai/connect/issues/425
=> Revert "test and fix dashboard routing (#319)"

src/pages/dashboard/Dashboard.tsx, src/pages/dashboard/components/DeviceList.tsx
First page load should be a little faster now. Devtools says DOMContentLoaded in the same time, but Finish goes from 1.5s to 0.5s
=> Remove duplicate devices query

src/api/devices.ts, src/pages/dashboard/Dashboard.tsx, src/pages/dashboard/activities/DeviceActivity.tsx, src/pages/dashboard/activities/SettingsActivity.tsx, src/pages/dashboard/components/DeviceList.tsx, src/utils/device.ts
Split from https://github.com/commaai/connect/pull/435, just a clean up
=> Remove shared device object

bun.lock, package.json, src/index.tsx, vite.config.ts
just updating existing dep + changing config
=> chore: fix solid-devtools

src/App.tsx
this gets rid of a ton of weird issues for me
=> fix: remove this top level suspense

src/pages/dashboard/components/RouteList.tsx
@sshane unlocked 2 seconds of latency with a red diff!
=> fix: dont wait here

src/pages/dashboard/activities/RouteActivity.tsx
split from https://github.com/commaai/connect/pull/428
=> fix: reset seek on route change

src/pages/dashboard/activities/DeviceActivity.tsx, src/pages/dashboard/activities/RouteActivity.tsx, src/pages/dashboard/components/RouteList.tsx
Just a vertical placeholder so cards don't jump
=> Add skeleton loader for new day headers

.github/workflows/build.yaml, test.sh
=> ci: bring back playwright cache

src/components/RouteStatistics.tsx, src/components/StatisticBar.tsx, src/utils/format.spec.ts, src/utils/format.ts
Part of https://github.com/commaai/connect/issues/472. Adding visual space for time makes it easier to read
=> Clearer stats

src/components/Timeline.tsx
fixes https://github.com/commaai/connect/issues/498
https://github.com/user-attachments/assets/d5f59ece-ce56-4c7e-bba0-e86609f631af
=> fix: timeline overflow

src/components/material/Card.tsx
Fixes https://github.com/commaai/connect/issues/244
=> Fix RouteCard overlap

src/pages/dashboard/activities/DeviceActivity.tsx
Reverts commaai/connect#495
Spacing is weird
=> Revert "Add all time label to device stats"

src/pages/dashboard/components/RouteList.tsx
fixes point 2 of https://github.com/commaai/connect/issues/506
https://github.com/user-attachments/assets/648cd0e6-0d7e-4569-9a30-8960dc5a344b
https://github.com/user-attachments/assets/f924c8cd-5ef0-4332-9cbf-b16173d9aabe
=> fix: prevent infinite loading of RouteList on shared device

src/pages/dashboard/Dashboard.tsx, src/pages/dashboard/activities/PairActivity.tsx
the device list doesn't refresh when you finish pairing your device. now, we refetch the list upon a successful pair
=> fix: refresh device list on pair

src/pages/dashboard/Dashboard.tsx
fixes point 1 of https://github.com/commaai/connect/issues/506
we could debate the logged out experience (maybe user should be able to view public route even if they aren't logged in), but that's a design conversation. this solves the current issue
https://github.com/user-attachments/assets/2abbe7e5-6c09-4d1c-888e-2804c6d8fee1
=> fix: redirect user if they arent logged in

src/pages/dashboard/Dashboard.tsx
Reverts commaai/connect#512
Can't do local dev without this logging you out decently often
=> Revert "fix: redirect user if they arent logged in"

src/components/DeviceLocation.tsx, src/components/RouteActions.tsx, src/components/RouteStaticMap.tsx, src/components/RouteVideoPlayer.tsx, src/components/StatisticBar.tsx, src/components/UploadQueue.tsx, src/pages/auth/auth.tsx, src/pages/auth/login.tsx, src/pages/dashboard/Dashboard.tsx, src/pages/dashboard/activities/DeviceActivity.tsx, src/pages/dashboard/activities/PairActivity.tsx, src/pages/dashboard/activities/RouteActivity.tsx, src/pages/dashboard/activities/SettingsActivity.tsx, src/pages/dashboard/components/DeviceList.tsx, src/pages/dashboard/components/RouteList.tsx, src/pages/offline.tsx, tailwind.config.ts
Define a consistent set of fonts (`text-xs`...`text-2xl`) and remove usages of the smallest font size
Keep around all of the font size definitions as some are used in the material components
#463
=> fix: rm smallest font size, use consistent font sizes across app

src/api/route.ts, src/pages/dashboard/activities/RouteActivity.tsx
instead of showing an empty space where the title (date) should be
=> fix(route): date loading

src/api/derived.ts, src/components/Timeline.tsx, src/pages/dashboard/activities/RouteActivity.tsx
Reverts commaai/connect#528
Broke https://github.com/commaai/connect/issues/549
=> Revert "feat(statistics): get route duration from log events"

src/App.browser.test.tsx, src/api/auth/client.ts, src/api/index.ts
we can use this to move "profile" out of the components and to global state
=> refactor(auth): accessToken is a signal

src/pages/dashboard/components/RouteList.tsx
=> fix(RouteList): increase subheading font size

src/components/RouteActions.tsx, src/components/material/Drawer.tsx, src/pages/dashboard/Dashboard.tsx
based on feedback from last dev call, speeding up the transitions, tweaking animation to be more like old connect
https://github.com/user-attachments/assets/7db41d0b-76b0-4369-af8b-8ab01acb1028
=> fix: speed up drawer open + open route

src/components/RouteActions.tsx
broke in dab9358279e4b9f9f25eade3b285da86dbd55810
=> fix(RouteActions): don't override icon padding

src/components/UploadQueue.tsx, src/components/material/Button.tsx, src/components/material/Icon.tsx, src/pages/dashboard/activities/DeviceActivity.tsx
add a 'text' button style and use that for the 'Cancel all' button
(The Button component need a refactor to split up the color and variant choice)
https://m3.material.io/components/all-buttons
| new | old |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/f8d49def-db65-480f-bae5-44f7d66f4bb2) |![image](https://github.com/user-attachments/assets/be95b37a-0004-45b4-8cd6-3a563420a9c9) |
=> feat(UploadQueue): improve 'Cancel all' button style

.github/tsc.json, .github/workflows/build.yaml
copied from https://github.com/actions/setup-node/blob/master/.github/tsc.json
closes #336
=> CI: add tsc problem matcher/annotations

src/pages/dashboard/activities/SettingsActivity.tsx
=> refactor(SettingsActivity): create DeviceSettingsForm component
